### ISSUE TITLE
No auto-photo on 2nd tap

### ISSUE THREAD

**Issue by theguardian** [Kegbot/kegbot-android#100]
http://old-forum.kegbot.org/discussions/kegbot-tablet-app/154-app-wont-automatically-take-picture-for-2nd-tap

Starting a pour on the 2nd tap in a 2-tap system does not generate an auto-photo countdown.

More info in a 3-kegboard, 6-tap system:
http://forum.kegbot.org/t/automatic-snapshot-not-working-on-2nd-taps-within-app/84

**Comment by jagee23** [comment]
I see this same issue.  However, starting pour on tap 2 as a guest and then claiming the pour initiates the auto-photo countdown.

**Comment by xxkap0wxx** [comment]
Yep - just trying to figure out if I'm crazy, but I'm glad to see this is being tracked.  Would really like to  have a fix here!

**Comment by arijbrown** [comment]
Also looking for this.  A big hole in our system

**Comment by xxkap0wxx** [comment]
@mik3y - any chance the kegbot god himself might take a look here?  Alas I am without the skills to fix but this is a huge issue for us here and I'd do most anything to see a fix.
