### ISSUE TITLE
Kegbot Slack?

### ISSUE THREAD

**Issue by rplankenhorn** [Kegbot/kegbot-android#116]
@mik3y Does anyone use #freenode anymore?  Have you considered creating a Slack organization for Kegbot?

It looks like this project is on the back burner for you.  I would like to start making minor improvements with the Android app and it would be great if we could have a shared chat platform for me to ask questions.

**Comment by mik3y** [comment]
Let's give it a shot! I set up a Slack org a while ago and never got around to doing anything with it. Here we go: https://github.com/Kegbot/kegbot-android/wiki/Developer-Discussion

If it takes off, I'll deprecate the IRC channel. Will limit this org to "developer stuff" for now as I think the forum is better for general usage discussion & HOWTOs, but will revisit after some mileage.

**Comment by mik3y** [comment]
Documented here! https://github.com/kegbot/kegbot-server#documentation-and-help
