### ISSUE TITLE
Crash when loading HomeActivity

### ISSUE THREAD

**Issue by rplankenhorn** [Kegbot/kegbot-android#129]
I am seeing a crash when trying to launch the HomeActivity after finishing the initial app configuration tutorial.  It is actually crashing on this line:  https://github.com/Kegbot/kegbot-android/blob/0cb79c6d140e4cceb752387944edff7839d02ce9/kegtab/src/main/java/org/kegbot/app/HomeActivity.java#L93.

I think it has something to do with how the `kegbot-api.jar` library is being imported because it can't find the `KegTab` class.

I'm going to see if I can isolate the commit that possibly caused the issue with git bisect but I also think it could be an issue with the version of Android Studio (4.0) I am running.

**Comment by rplankenhorn** [comment]
I performed a git bisect and was able to determine that this is the bad commit:  https://github.com/Kegbot/kegbot-android/commit/9e9f835df27556c260232bb99a4401e97f45bff9

**Comment by rplankenhorn** [comment]
@mik3y Any ideas?  I think it has something to do with the change from compile to implementation for pulling in libraries.  I also see this issue when building a debug apk.  I even extracted the apk to a folder to see if the jar was included and it wasn't.

**Comment by rplankenhorn** [comment]
I tried taking the latest published APK from the tagged releases page and installing it on my tablet but got the same crash.  I'm still trying to figure out what changes need to be made to the gradle file to fix the issue but I think this means that it isn't an issue with my local machine.

**Comment by rplankenhorn** [comment]
After researching this a bit more, the exception being thrown is a `NoClassDefFoundError`.  This means that the class is available at build time but for some reason isn't accessible at runtime.  My guess is that it has something to do with how the protoc files are being generated on my machine.

**Comment by rplankenhorn** [comment]
I'm actually seeing the same issue when I download the b88 APK and install it.  The issue isn't present when I use the the previous b84 APK.

**Comment by mik3y** [comment]
Fixed in #133

**Comment by mik3y** [comment]
Reopening, this crash (or something very similar) is still an issue in latest build.

**Comment by mik3y** [comment]
Fixed in #135!
