### ISSUE TITLE
2nd Tap always starts hidden in 2-tap system

### ISSUE THREAD

**Issue by theguardian** [Kegbot/kegbot-android#99]
When configured with two taps, the second tap always starts hidden.  Whenever the tablet is restarted or kegbot-android crashes (rarely), the second tap has to manually be made visible again.

**Comment by EagleOne42** [comment]
I have 3 taps listed on mine and the 2nd tap does this too.  The 1st and 3rd will be there but the 2nd will go away.

**Comment by dboyd13** [comment]
+1 - I have the same issue with a 2 tap system

**Comment by dboyd13** [comment]
+1

**Comment by dboyd13** [comment]
@mik3y - Had a quick look through your code, it appears that the 'ON/OFF' toggle for each tap is not saved into preferences currently. Is this something you'd be looking to add to the KegBot android app in the near future?
